/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.29.0
 * source: io/common/protocols.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace io {
    export enum PassProtocol {
        PASS_PROTOCOL_DO_NOT_USE = 0,
        RAW_PROTOCOL = 1,
        V1_PROTOCOL = 2,
        FLIGHT_PROTOCOL = 3,
        MEMBERSHIP = 100,
        SINGLE_USE_COUPON = 101,
        EVENT_TICKETING = 102
    }
    export enum ProtocolCommonEvents {
        PROTOCOL_COMMON_EVENTS_DO_NOT_USE = 0,
        EVENT_OBJECT_CREATED = 1,
        EVENT_OBJECT_UPDATED = 2,
        EVENT_OBJECT_EXPIRED = 3,
        EVENT_OBJECT_DELETED = 4,
        EVENT_PASS_ISSUED = 5,
        EVENT_PASS_INSTALLED = 6,
        EVENT_PASS_UNINSTALLED = 7,
        EVENT_PASS_INVALIDATED = 8
    }
}
